services:
  erddap:
    image: axiom/docker-erddap:2.23-jdk17-openjdk
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./erddap/conf/config.sh:/usr/local/tomcat/bin/config.sh
      - ./erddap/conf/robots.txt:/usr/local/tomcat/webapps/ROOT/robots.txt
      - ./erddap/content:/usr/local/tomcat/content/erddap
      - ./erddap/data:/erddapData
      - ./datasets:/datasets
    environment:
      #note: these can also be set in /usr/local/tomcat/bin/config.sh
      ERDDAP_MIN_MEMORY: 1G
      ERDDAP_MAX_MEMORY: 2G
      ERDDAP_bigParentDirectory: /erddapData/
      ERDDAP_baseUrl: http://localhost:8080
      ERDDAP_baseHttpsUrl: https://localhost:8080
      ERDDAP_flagKeyKey: change-this-value!!
      ERDDAP_emailEverythingTo: this+goes+nowhere@doesnotexist.ioos.us
      ERDDAP_emailDailyReportTo:
      ERDDAP_emailFromAddress:
      ERDDAP_emailUserName:
      ERDDAP_emailPassword:
      ERDDAP_emailProperties:
      ERDDAP_emailSmtpHost:
      ERDDAP_emailSmtpPort:
      ERDDAP_adminInstitution: Integrated Ocean Observing System (IOOS)
      ERDDAP_adminInstitutionUrl: https://ioos.github.io/
      ERDDAP_adminIndividualName: IOOS Data Manager
      ERDDAP_adminPosition: Data Manager
      ERDDAP_adminPhone: "240-533-9444"
      ERDDAP_adminAddress: "1315 East-West Highway 2nd Floor"
      ERDDAP_adminCity: Silver Spring
      ERDDAP_adminStateOrProvince: MD
      ERDDAP_adminPostalCode: "20910"
      ERDDAP_adminCountry: USA
      ERDDAP_adminEmail: data.ioos@noaa.gov
