ERDDAP_bigParentDirectory="/erddapData/"
ERDDAP_baseUrl="http://localhost:8080"
ERDDAP_baseHttpsUrl="http://localhost:8080"
ERDDAP_flagKeyKey="4a0c345f-d494-4edc-b8c7-640c6d99f4b1"

ERDDAP_emailEverythingTo="this+goes+nowhere@doesnotexist.ioos.us"
ERDDAP_emailDailyReportsTo=""
ERDDAP_emailFromAddress=""
ERDDAP_emailUserName=""
ERDDAP_emailPassword=""
ERDDAP_emailProperties=""
ERDDAP_emailSmtpHost=""
ERDDAP_emailSmtpPort=""

ERDDAP_adminInstitution="Integrated Ocean Observing System (IOOS)"
ERDDAP_adminInstitutionUrl="https://ioos.github.io/"
ERDDAP_adminIndividualName="Micah Wengren"
ERDDAP_adminPosition="Data Manager"
ERDDAP_adminPhone="240-533-9441"
ERDDAP_adminAddress="1315 East-West Highway 2nd Floor"
ERDDAP_adminCity="Silver Spring"
ERDDAP_adminStateOrProvince="MD"
ERDDAP_adminPostalCode="20910"
ERDDAP_adminCountry="USA"
ERDDAP_adminEmail="micah.wengren@noaa.gov"
