ERDDAP_bigParentDirectory="/erddapData/"
ERDDAP_baseUrl="https://dev.cioosatlantic.ca"
ERDDAP_baseHttpsUrl="https://dev.cioosatlantic.ca"
ERDDAP_flagKeyKey="4a0c345f-d494-4edc-b8c7-640c6d99f4b1"

ERDDAP_emailEverythingTo="youremail@yourInstitution.edu"
ERDDAP_emailDailyReportsTo=""
ERDDAP_emailFromAddress=""
ERDDAP_emailUserName=""
ERDDAP_emailPassword=""
ERDDAP_emailProperties=""
ERDDAP_emailSmtpHost=""
ERDDAP_emailSmtpPort=""

ERDDAP_adminInstitution="CIOOS Atlantic Regional Association"
ERDDAP_adminInstitutionUrl="https://www.cioos.ca/atlantic"
ERDDAP_adminIndividualName="Data Management Team"
ERDDAP_adminPosition="Data Managers"
ERDDAP_adminPhone="1-888-FOR-DATA"
ERDDAP_adminAddress="155 University Ave #302"
ERDDAP_adminCity="Toronto"
ERDDAP_adminStateOrProvince="ON"
ERDDAP_adminPostalCode="M5H 3B7"
ERDDAP_adminCountry="Canada"
ERDDAP_adminEmail="atlantic@cioos.ca"
